/*
 * Engineering Ingegneria Informatica S.p.A.
 *
 * Copyright (C) 2023 Regione Emilia-Romagna
 * <p/>
 * This program is free software: you can redistribute it and/or modify it under the terms of
 * the GNU Affero General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 * <p/>
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 * <p/>
 * You should have received a copy of the GNU Affero General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */

package it.eng.parer.grantedEntity;

import java.io.Serializable;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator edited by fioravanti_f
 */
@Entity
@Table(schema = "SACER_IAM", name = "DEC_COL_QUERY_MODELLO_COMUNIC")
public class SIDecColQueryModelloComunic implements Serializable {
    private SIDecQueryModelloComunic siDecQueryModelloComunic;
    private Long idColQueryModelloComunic;
    private String nmCol;
    private Long pgPosizCol;

    public SIDecColQueryModelloComunic() {/* Hibernate */
    }

    public SIDecColQueryModelloComunic(Long idColQueryModelloComunic) {
        this.idColQueryModelloComunic = idColQueryModelloComunic;
    }

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
    @JoinColumn(name = "ID_QUERY_MODELLO_COMUNIC", nullable = false)
    public SIDecQueryModelloComunic getSiDecQueryModelloComunic() {
        return siDecQueryModelloComunic;
    }

    public void setSiDecQueryModelloComunic(SIDecQueryModelloComunic siDecQueryModelloComunic) {
        this.siDecQueryModelloComunic = siDecQueryModelloComunic;
    }

    @Id
    @Column(name = "ID_COL_QUERY_MODELLO_COMUNIC")
    public Long getIdColQueryModelloComunic() {
        return idColQueryModelloComunic;
    }

    public void setIdColQueryModelloComunic(Long idColQueryModelloComunic) {
        this.idColQueryModelloComunic = idColQueryModelloComunic;
    }

    @Basic
    @Column(name = "NM_COL", nullable = false, length = 100)
    public String getNmCol() {
        return nmCol;
    }

    public void setNmCol(String nmCol) {
        this.nmCol = nmCol;
    }

    @Basic
    @Column(name = "PG_POSIZ_COL")
    public Long getPgPosizCol() {
        return pgPosizCol;
    }

    public void setPgPosizCol(Long pgPosizCol) {
        this.pgPosizCol = pgPosizCol;
    }
}
