/*
 * Engineering Ingegneria Informatica S.p.A.
 *
 * Copyright (C) 2023 Regione Emilia-Romagna
 * <p/>
 * This program is free software: you can redistribute it and/or modify it under the terms of
 * the GNU Affero General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 * <p/>
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 * <p/>
 * You should have received a copy of the GNU Affero General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */

package it.eng.parer.grantedEntity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import it.eng.parer.entity.constraint.SIOrgEnteSiam.TiEnteConvenz;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator edited by fioravanti_f
 */
@Entity
@Table(schema = "SACER_IAM", name = "ORG_ENTE_SIAM")
public class SIOrgEnteSiam implements Serializable {

    private String cdCapSedeLegale;
    private String cdEnteConvenz;
    private String cdFisc;
    private String cdNazioneSedeLegale;
    private List<SIDecUsoModelloComunic> decUsoModelloComunics = new ArrayList<>();
    private String dsCittaSedeLegale;
    private String dsViaSedeLegale;
    private Date dtCessazione;
    private Date dtIniVal;
    private BigDecimal idAmbitoTerrit;
    private Long idEnteSiam;
    private String nmEnteSiam;
    private SIOrgAmbienteEnteConvenz siOrgAmbienteEnteConvenz;
    private SIOrgEnteSiam siOrgEnteConvenz;
    private List<SIOrgEnteConvenzOrg> orgEnteConvenzOrgs = new ArrayList<>();
    private List<SIOrgEnteSiam> orgEnteConvenzs = new ArrayList<>();
    private List<SIOrgAccordoEnte> orgAccordoEntes = new ArrayList<>();
    private String tiCdEnteConvenz;
    private TiEnteConvenz tiEnteConvenz;
    private List<UsrUser> usrUsers = new ArrayList<>();

    public SIOrgEnteSiam() {/* Hibernate */
    }

    public SIOrgEnteSiam(Long idEnteSiam) {
        this.idEnteSiam = idEnteSiam;
    }

    @Basic
    @Column(name = "CD_CAP_SEDE_LEGALE", length = 5)
    public String getCdCapSedeLegale() {
        return cdCapSedeLegale;
    }

    public void setCdCapSedeLegale(String cdCapSedeLegale) {
        this.cdCapSedeLegale = cdCapSedeLegale;
    }

    @Basic
    @Column(name = "CD_ENTE_CONVENZ", nullable = false, length = 100)
    public String getCdEnteConvenz() {
        return cdEnteConvenz;
    }

    public void setCdEnteConvenz(String cdEnteConvenz) {
        this.cdEnteConvenz = cdEnteConvenz;
    }

    @Basic
    @Column(name = "CD_FISC", length = 11)
    public String getCdFisc() {
        return cdFisc;
    }

    public void setCdFisc(String cdFisc) {
        this.cdFisc = cdFisc;
    }

    @Basic
    @Column(name = "CD_NAZIONE_SEDE_LEGALE", nullable = false, length = 254)
    public String getCdNazioneSedeLegale() {
        return cdNazioneSedeLegale;
    }

    public void setCdNazioneSedeLegale(String cdNazioneSedeLegale) {
        this.cdNazioneSedeLegale = cdNazioneSedeLegale;
    }

    @OneToMany(mappedBy = "siOrgEnteConvenz", cascade = CascadeType.MERGE)
    public List<SIDecUsoModelloComunic> getDecUsoModelloComunics() {
        return decUsoModelloComunics;
    }

    public void setDecUsoModelloComunics(List<SIDecUsoModelloComunic> decUsoModelloComunics) {
        this.decUsoModelloComunics = decUsoModelloComunics;
    }

    @Basic
    @Column(name = "DS_CITTA_SEDE_LEGALE", length = 254)
    public String getDsCittaSedeLegale() {
        return dsCittaSedeLegale;
    }

    public void setDsCittaSedeLegale(String dsCittaSedeLegale) {
        this.dsCittaSedeLegale = dsCittaSedeLegale;
    }

    @Basic
    @Column(name = "DS_VIA_SEDE_LEGALE", length = 254)
    public String getDsViaSedeLegale() {
        return dsViaSedeLegale;
    }

    public void setDsViaSedeLegale(String dsViaSedeLegale) {
        this.dsViaSedeLegale = dsViaSedeLegale;
    }

    @Basic
    @Column(name = "DT_CESSAZIONE")
    @Temporal(TemporalType.TIMESTAMP)
    public Date getDtCessazione() {
        return dtCessazione;
    }

    public void setDtCessazione(Date dtCessazione) {
        this.dtCessazione = dtCessazione;
    }

    @Basic
    @Column(name = "DT_INI_VAL", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    public Date getDtIniVal() {
        return dtIniVal;
    }

    public void setDtIniVal(Date dtIniVal) {
        this.dtIniVal = dtIniVal;
    }

    // @Basic
    // @Column(name = "FL_ENTE_REGIONE", nullable = false, length = 1)
    // public String getFlEnteRegione() {
    // return flEnteRegione;
    // }
    //
    // public void setFlEnteRegione(String flEnteRegione) {
    // this.flEnteRegione = flEnteRegione;
    // }

    @Column(name = "ID_AMBITO_TERRIT")
    public BigDecimal getIdAmbitoTerrit() {
        return this.idAmbitoTerrit;
    }

    public void setIdAmbitoTerrit(BigDecimal idAmbitoTerrit) {
        this.idAmbitoTerrit = idAmbitoTerrit;
    }

    @Id
    @Column(name = "ID_ENTE_SIAM")
    public Long getIdEnteSiam() {
        return idEnteSiam;
    }

    public void setIdEnteSiam(Long idEnteSiam) {
        this.idEnteSiam = idEnteSiam;
    }

    @Basic
    @Column(name = "NM_ENTE_SIAM", nullable = false, length = 254)
    public String getNmEnteSiam() {
        return nmEnteSiam;
    }

    public void setNmEnteSiam(String nmEnteSiam) {
        this.nmEnteSiam = nmEnteSiam;
    }

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
    @JoinColumn(name = "ID_AMBIENTE_ENTE_CONVENZ")
    public SIOrgAmbienteEnteConvenz getSiOrgAmbienteEnteConvenz() {
        return siOrgAmbienteEnteConvenz;
    }

    public void setSiOrgAmbienteEnteConvenz(SIOrgAmbienteEnteConvenz siOrgAmbienteEnteConvenz) {
        this.siOrgAmbienteEnteConvenz = siOrgAmbienteEnteConvenz;
    }

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
    @JoinColumn(name = "ID_ENTE_CONVENZ_NUOVO")
    public SIOrgEnteSiam getSiOrgEnteConvenz() {
        return siOrgEnteConvenz;
    }

    public void setSiOrgEnteConvenz(SIOrgEnteSiam siOrgEnteConvenz) {
        this.siOrgEnteConvenz = siOrgEnteConvenz;
    }

    @OneToMany(mappedBy = "siOrgEnteConvenz", cascade = CascadeType.MERGE)
    public List<SIOrgEnteConvenzOrg> getOrgEnteConvenzOrgs() {
        return orgEnteConvenzOrgs;
    }

    public void setOrgEnteConvenzOrgs(List<SIOrgEnteConvenzOrg> orgEnteConvenzOrgs) {
        this.orgEnteConvenzOrgs = orgEnteConvenzOrgs;
    }

    @OneToMany(mappedBy = "siOrgEnteConvenz", cascade = CascadeType.MERGE)
    public List<SIOrgEnteSiam> getOrgEnteConvenzs() {
        return orgEnteConvenzs;
    }

    public void setOrgEnteConvenzs(List<SIOrgEnteSiam> orgEnteConvenzs) {
        this.orgEnteConvenzs = orgEnteConvenzs;
    }

    @OneToMany(mappedBy = "siOrgEnteConvenz", cascade = CascadeType.MERGE)
    public List<SIOrgAccordoEnte> getOrgAccordoEntes() {
        return orgAccordoEntes;
    }

    public void setOrgAccordoEntes(List<SIOrgAccordoEnte> orgAccordoEntes) {
        this.orgAccordoEntes = orgAccordoEntes;
    }

    @Basic
    @Column(name = "TI_CD_ENTE_CONVENZ", nullable = false, length = 20)
    public String getTiCdEnteConvenz() {
        return tiCdEnteConvenz;
    }

    public void setTiCdEnteConvenz(String tiCdEnteConvenz) {
        this.tiCdEnteConvenz = tiCdEnteConvenz;
    }

    @Enumerated(EnumType.STRING)
    @Column(name = "TI_ENTE_CONVENZ")
    public TiEnteConvenz getTiEnteConvenz() {
        return this.tiEnteConvenz;
    }

    public void setTiEnteConvenz(TiEnteConvenz tiEnteConvenz) {
        this.tiEnteConvenz = tiEnteConvenz;
    }

    // bi-directional many-to-one association to UsrUser
    @OneToMany(mappedBy = "siOrgEnteSiam")
    public List<UsrUser> getUsrUsers() {
        return this.usrUsers;
    }

    public void setUsrUsers(List<UsrUser> usrUsers) {
        this.usrUsers = usrUsers;
    }

}
