name: Maven compile
on: push
jobs:
  maven-compile:
    env:
      JAVA_VERSION: '17'
    steps:
    - uses: RegioneER/parer-github-template/.github/workflows/compile.yml@main
      with:
        java: ${{env.JAVA_VERSION}}
