name: Create Maven Release
env:
  JAVA_VERSION: '17'
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number"
        required: true
        type: string
      java_version:
        description: "Java version"
        required: false
        type: string
        default: '17'        
jobs:
  maven-release:
    uses: RegioneER/parer-github-template/.github/workflows/release.yml@v1
    with:
      version: ${{ inputs.version }}
      java_version: ${{ inputs.java_version }}