name: Create Maven Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number"
jobs:
  maven-release:
    uses: RegioneER/parer-github-template/.github/workflows/release.yml
