name: Create Maven Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number"
        required: true
        type: string
jobs:
  maven-release:
    uses: RegioneER/parer-github-template/.github/workflows/release.yml@main
    with:
      version: ${{ inputs.version }}
    